import '~/styles/globals.css'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

import { TRPCReactProvider } from '~/trpc/client'
import Header from '~/components/layout/header'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export default function RootLayout({
  children
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col items-center justify-start ${inter.variable} font-inter antialiased`}
      >
        <TRPCReactProvider>
          <Header />
          <main className="gradient-border-y gradient-border-l flex w-full max-w-4xl flex-grow flex-col items-center justify-start p-4">
            {children}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
